// Code generated by gosx. DO NOT EDIT.
package modules

import (
	_ "gridiron-2000/app"
	_ "gridiron-2000/app/admin"
	_ "gridiron-2000/app/board"
	_ "gridiron-2000/app/draft"
	_ "gridiron-2000/app/login"
	_ "gridiron-2000/app/matchups"
	_ "gridiron-2000/app/pickem"
	_ "gridiron-2000/app/scoring"
	_ "gridiron-2000/app/team"
	_ "gridiron-2000/app/wire"
)
