// Code generated by gosx. DO NOT EDIT.
package modules

import (
	_ "gridiron-2000/app"
	_ "gridiron-2000/app/activity"
	_ "gridiron-2000/app/admin"
	_ "gridiron-2000/app/blitz"
	_ "gridiron-2000/app/board"
	_ "gridiron-2000/app/commissioner"
	_ "gridiron-2000/app/draft"
	_ "gridiron-2000/app/guide"
	_ "gridiron-2000/app/help"
	_ "gridiron-2000/app/help/_topic_id"
	_ "gridiron-2000/app/join"
	_ "gridiron-2000/app/login"
	_ "gridiron-2000/app/matchups"
	_ "gridiron-2000/app/open-source"
	_ "gridiron-2000/app/pickem"
	_ "gridiron-2000/app/players"
	_ "gridiron-2000/app/privacy"
	_ "gridiron-2000/app/scoring"
	_ "gridiron-2000/app/settings"
	_ "gridiron-2000/app/team"
	_ "gridiron-2000/app/terms"
	_ "gridiron-2000/app/trades"
	_ "gridiron-2000/app/wire"
)
