package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// runtimeEnvFileName is the file the app loads at boot when present,
// beside league.db (owner decision, resolving the design's open decision
// 6): "The APP loads it itself at boot from <data dir>/runtime.env (0600,
// beside league.db), merging under real env (real env wins). No
// supervisor/compose coupling."
const runtimeEnvFileName = "runtime.env"

// runtimeEnvPath returns the runtime.env path for a data directory (the
// directory holding DATA_FILE — the same directory league.json's lookup
// rule 4, config.go:396, already searches).
func runtimeEnvPath(dataDir string) string {
	return filepath.Join(dataDir, runtimeEnvFileName)
}

// loadRuntimeEnvFile reads runtime.env, if present, and sets any key not
// already present in the process environment. It never overrides an
// explicitly set environment variable ("merging under real env, real env
// wins" — owner decision). Absence is not an error: an instance that never
// completed the wizard, or a Kubernetes bundle-mode instance (a later
// slice), simply has no such file.
func loadRuntimeEnvFile(dataDir string) error {
	path := runtimeEnvPath(dataDir)
	raw, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return fmt.Errorf("read %s: %w", path, err)
	}
	for lineNo, line := range strings.Split(string(raw), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		key, value, ok := strings.Cut(line, "=")
		if !ok {
			return fmt.Errorf("%s:%d: missing '='", path, lineNo+1)
		}
		key = strings.TrimSpace(key)
		if key == "" {
			return fmt.Errorf("%s:%d: empty key", path, lineNo+1)
		}
		if strings.TrimSpace(os.Getenv(key)) != "" {
			continue // real env wins
		}
		if err := os.Setenv(key, strings.TrimSpace(value)); err != nil {
			return fmt.Errorf("set %s: %w", key, err)
		}
	}
	return nil
}

// renderRuntimeEnv builds runtime.env's exact contents (design section
// 4.3/4.5): the env-twin values that are not league.json fields
// (COMMISSIONER_EMAILS, IDENTITY_ALIASES) plus a freshly generated
// SESSION_SECRET, so a wizard-completed instance never runs on the
// hard-coded local-dev default (AppConfigFromEnv's own fallback exists
// only for a checkout that has not run setup at all).
func renderRuntimeEnv(commissionerEmail string, aliases []identityAliasPair, sessionSecret string) []byte {
	var b strings.Builder
	b.WriteString("# Generated by the Gridiron setup wizard. Do not edit by hand; re-run setup instead.\n")
	fmt.Fprintf(&b, "COMMISSIONER_EMAILS=%s\n", commissionerEmail)
	if len(aliases) > 0 {
		pairs := make([]string, 0, len(aliases))
		for _, alias := range aliases {
			pairs = append(pairs, alias.Alias+"="+alias.Canonical)
		}
		fmt.Fprintf(&b, "IDENTITY_ALIASES=%s\n", strings.Join(pairs, ","))
	}
	fmt.Fprintf(&b, "SESSION_SECRET=%s\n", sessionSecret)
	return []byte(b.String())
}

// identityAliasPair mirrors setupwizard.IdentityAlias without importing
// that package here, keeping this file's dependency surface to what it
// actually needs (a plain data shape). wizard_commit.go converts between
// the two at the one call site.
type identityAliasPair struct {
	Alias     string
	Canonical string
}

// writeFileAtomic writes data to path via a temp file in the same
// directory, fsync, then rename (design section 4.5: "tmp -> fsync ->
// rename" for both runtime.env and league.json) — a crash mid-write
// leaves the old file (or no file) in place, never a truncated one.
func writeFileAtomic(path string, data []byte, perm os.FileMode) error {
	dir := filepath.Dir(path)
	tmp, err := os.CreateTemp(dir, ".gridiron-setup-tmp-*")
	if err != nil {
		return fmt.Errorf("create temp file in %s: %w", dir, err)
	}
	tmpPath := tmp.Name()
	defer func() { _ = os.Remove(tmpPath) }() // no-op once the rename below succeeds
	if _, err := tmp.Write(data); err != nil {
		_ = tmp.Close()
		return fmt.Errorf("write %s: %w", tmpPath, err)
	}
	if err := tmp.Chmod(perm); err != nil {
		_ = tmp.Close()
		return fmt.Errorf("chmod %s: %w", tmpPath, err)
	}
	if err := tmp.Sync(); err != nil {
		_ = tmp.Close()
		return fmt.Errorf("fsync %s: %w", tmpPath, err)
	}
	if err := tmp.Close(); err != nil {
		return fmt.Errorf("close %s: %w", tmpPath, err)
	}
	if err := os.Rename(tmpPath, path); err != nil {
		return fmt.Errorf("rename %s to %s: %w", tmpPath, path, err)
	}
	return nil
}
