package fantasy

// OfflinePool returns an embedded, approximate draft pool. It exists so an
// eight-team, fifteen-round draft can run with zero network access and no
// API key. Ranks reflect early-2026 consensus and are intentionally coarse;
// a Tank01 sync replaces this pool with live ADP the moment a key is set.
// Bye weeks are omitted (unknown without a live schedule source).
func OfflinePool() []Player {
	rows := []struct {
		name string
		pos  string
		team string
		proj float64
	}{
		{"Ja'Marr Chase", "WR", "CIN", 20.8},
		{"Bijan Robinson", "RB", "ATL", 20.1},
		{"Justin Jefferson", "WR", "MIN", 19.6},
		{"Jahmyr Gibbs", "RB", "DET", 19.4},
		{"Saquon Barkley", "RB", "PHI", 19.0},
		{"CeeDee Lamb", "WR", "DAL", 18.3},
		{"Puka Nacua", "WR", "LAR", 18.1},
		{"Amon-Ra St. Brown", "WR", "DET", 17.9},
		{"Malik Nabers", "WR", "NYG", 17.6},
		{"Christian McCaffrey", "RB", "SF", 17.5},
		{"Nico Collins", "WR", "HOU", 17.2},
		{"Ashton Jeanty", "RB", "LV", 17.0},
		{"De'Von Achane", "RB", "MIA", 16.9},
		{"Derrick Henry", "RB", "BAL", 16.8},
		{"Brian Thomas Jr.", "WR", "JAX", 16.6},
		{"A.J. Brown", "WR", "PHI", 16.5},
		{"Drake London", "WR", "ATL", 16.4},
		{"Josh Jacobs", "RB", "GB", 16.3},
		{"Brock Bowers", "TE", "LV", 15.8},
		{"Jonathan Taylor", "RB", "IND", 16.1},
		{"Ladd McConkey", "WR", "LAC", 15.9},
		{"Bucky Irving", "RB", "TB", 15.8},
		{"Kyren Williams", "RB", "LAR", 15.6},
		{"Tee Higgins", "WR", "CIN", 15.5},
		{"Trey McBride", "TE", "ARI", 14.9},
		{"James Cook", "RB", "BUF", 15.3},
		{"Jaxon Smith-Njigba", "WR", "SEA", 15.2},
		{"Terry McLaurin", "WR", "WAS", 15.0},
		{"Garrett Wilson", "WR", "NYJ", 14.9},
		{"Chase Brown", "RB", "CIN", 14.8},
		{"Tyreek Hill", "WR", "MIA", 14.7},
		{"Davante Adams", "WR", "LAR", 14.6},
		{"Omarion Hampton", "RB", "LAC", 14.5},
		{"Kenneth Walker III", "RB", "SEA", 14.4},
		{"Breece Hall", "RB", "NYJ", 14.3},
		{"Marvin Harrison Jr.", "WR", "ARI", 14.2},
		{"DK Metcalf", "WR", "PIT", 14.1},
		{"Rashee Rice", "WR", "KC", 14.0},
		{"Josh Allen", "QB", "BUF", 23.5},
		{"Lamar Jackson", "QB", "BAL", 23.2},
		{"Chuba Hubbard", "RB", "CAR", 13.8},
		{"Alvin Kamara", "RB", "NO", 13.7},
		{"DJ Moore", "WR", "CHI", 13.6},
		{"Jayden Daniels", "QB", "WAS", 22.4},
		{"Jalen Hurts", "QB", "PHI", 22.1},
		{"Courtland Sutton", "WR", "DEN", 13.4},
		{"Zay Flowers", "WR", "BAL", 13.3},
		{"Xavier Worthy", "WR", "KC", 13.2},
		{"George Kittle", "TE", "SF", 12.9},
		{"Mike Evans", "WR", "TB", 13.1},
		{"D'Andre Swift", "RB", "CHI", 12.9},
		{"Joe Burrow", "QB", "CIN", 21.8},
		{"Aaron Jones", "RB", "MIN", 12.7},
		{"James Conner", "RB", "ARI", 12.6},
		{"TreVeyon Henderson", "RB", "NE", 12.5},
		{"RJ Harvey", "RB", "DEN", 12.4},
		{"Quinshon Judkins", "RB", "CLE", 12.3},
		{"Tetairoa McMillan", "WR", "CAR", 12.2},
		{"Travis Hunter", "WR", "JAX", 12.1},
		{"Jaylen Waddle", "WR", "MIA", 12.0},
		{"Jameson Williams", "WR", "DET", 11.9},
		{"Sam LaPorta", "TE", "DET", 11.4},
		{"Emeka Egbuka", "WR", "TB", 11.7},
		{"Chris Godwin", "WR", "TB", 11.6},
		{"Chris Olave", "WR", "NO", 11.5},
		{"Jerry Jeudy", "WR", "CLE", 11.4},
		{"George Pickens", "WR", "DAL", 11.3},
		{"Kaleb Johnson", "RB", "PIT", 11.2},
		{"Tony Pollard", "RB", "TEN", 11.1},
		{"Zach Charbonnet", "RB", "SEA", 11.0},
		{"Patrick Mahomes", "QB", "KC", 20.9},
		{"Baker Mayfield", "QB", "TB", 20.7},
		{"T.J. Hockenson", "TE", "MIN", 10.8},
		{"Calvin Ridley", "WR", "TEN", 10.8},
		{"Rome Odunze", "WR", "CHI", 10.7},
		{"Jordan Addison", "WR", "MIN", 10.6},
		{"Stefon Diggs", "WR", "NE", 10.5},
		{"Khalil Shakir", "WR", "BUF", 10.4},
		{"Jakobi Meyers", "WR", "LV", 10.3},
		{"Kyler Murray", "QB", "ARI", 20.2},
		{"Brock Purdy", "QB", "SF", 20.0},
		{"Travis Kelce", "TE", "KC", 10.2},
		{"Mark Andrews", "TE", "BAL", 10.0},
		{"David Njoku", "TE", "CLE", 9.9},
		{"Evan Engram", "TE", "DEN", 9.8},
		{"Najee Harris", "RB", "LAC", 10.1},
		{"Javonte Williams", "RB", "DAL", 10.0},
		{"Jaylen Warren", "RB", "PIT", 9.9},
		{"Isiah Pacheco", "RB", "KC", 9.8},
		{"Tyjae Spears", "RB", "TEN", 9.7},
		{"Tyler Allgeier", "RB", "ATL", 9.6},
		{"Rhamondre Stevenson", "RB", "NE", 9.5},
		{"Caleb Williams", "QB", "CHI", 19.6},
		{"Justin Herbert", "QB", "LAC", 19.5},
		{"Bo Nix", "QB", "DEN", 19.4},
		{"Jared Goff", "QB", "DET", 19.2},
		{"Ricky Pearsall", "WR", "SF", 9.9},
		{"Jauan Jennings", "WR", "SF", 9.8},
		{"Deebo Samuel", "WR", "WAS", 9.7},
		{"Cooper Kupp", "WR", "SEA", 9.6},
		{"Keon Coleman", "WR", "BUF", 9.5},
		{"Michael Pittman Jr.", "WR", "IND", 9.4},
		{"Josh Downs", "WR", "IND", 9.3},
		{"Darnell Mooney", "WR", "ATL", 9.2},
		{"Rashid Shaheed", "WR", "NO", 9.1},
		{"Matthew Golden", "WR", "GB", 9.0},
		{"Jayden Higgins", "WR", "HOU", 8.9},
		{"Tre Harris", "WR", "LAC", 8.8},
		{"Luther Burden III", "WR", "CHI", 8.7},
		{"Tucker Kraft", "TE", "GB", 9.4},
		{"Jake Ferguson", "TE", "DAL", 9.2},
		{"Dallas Goedert", "TE", "PHI", 9.0},
		{"Tyler Warren", "TE", "IND", 8.9},
		{"Colston Loveland", "TE", "CHI", 8.7},
		{"Dalton Kincaid", "TE", "BUF", 8.5},
		{"Hunter Henry", "TE", "NE", 8.3},
		{"Zach Ertz", "TE", "WAS", 8.1},
		{"Justin Fields", "QB", "NYJ", 18.9},
		{"Dak Prescott", "QB", "DAL", 18.7},
		{"Drake Maye", "QB", "NE", 18.5},
		{"Jordan Love", "QB", "GB", 18.3},
		{"C.J. Stroud", "QB", "HOU", 18.1},
		{"Tua Tagovailoa", "QB", "MIA", 17.9},
		{"Trevor Lawrence", "QB", "JAX", 17.7},
		{"Michael Penix Jr.", "QB", "ATL", 17.5},
		{"J.J. McCarthy", "QB", "MIN", 17.3},
		{"Cam Ward", "QB", "TEN", 17.1},
		{"Bryce Young", "QB", "CAR", 16.9},
		{"Matthew Stafford", "QB", "LAR", 16.7},
		{"Sam Darnold", "QB", "SEA", 16.5},
		{"Geno Smith", "QB", "LV", 16.3},
		{"Nick Chubb", "RB", "HOU", 9.3},
		{"Joe Mixon", "RB", "HOU", 9.1},
		{"Austin Ekeler", "RB", "WAS", 8.9},
		{"Rachaad White", "RB", "TB", 8.7},
		{"Jerome Ford", "RB", "CLE", 8.5},
		{"Jordan Mason", "RB", "MIN", 8.4},
		{"Braelon Allen", "RB", "NYJ", 8.3},
		{"Ray Davis", "RB", "BUF", 8.2},
		{"Cam Skattebo", "RB", "NYG", 8.1},
		{"Trey Benson", "RB", "ARI", 8.0},
		{"Isaac Guerendo", "RB", "SF", 7.9},
		{"Blake Corum", "RB", "LAR", 7.8},
		{"Will Shipley", "RB", "PHI", 7.7},
		{"Kareem Hunt", "RB", "KC", 7.6},
		{"Roschon Johnson", "RB", "CHI", 7.5},
		{"Dylan Sampson", "RB", "CLE", 7.4},
		{"Alec Pierce", "WR", "IND", 8.6},
		{"Wan'Dale Robinson", "WR", "NYG", 8.5},
		{"Marvin Mims", "WR", "DEN", 8.4},
		{"Quentin Johnston", "WR", "LAC", 8.3},
		{"Cedric Tillman", "WR", "CLE", 8.2},
		{"Romeo Doubs", "WR", "GB", 8.1},
		{"Dontayvion Wicks", "WR", "GB", 8.0},
		{"Hollywood Brown", "WR", "KC", 7.9},
		{"Jaylin Noel", "WR", "HOU", 7.8},
		{"Kyle Williams", "WR", "NE", 7.7},
		{"Jack Bech", "WR", "LV", 7.6},
		{"Brandon Aubrey", "K", "DAL", 9.2},
		{"Jake Bates", "K", "DET", 8.6},
		{"Cameron Dicker", "K", "LAC", 8.5},
		{"Chris Boswell", "K", "PIT", 8.4},
		{"Ka'imi Fairbairn", "K", "HOU", 8.3},
		{"Harrison Butker", "K", "KC", 8.2},
		{"Tyler Bass", "K", "BUF", 8.0},
		{"Evan McPherson", "K", "CIN", 7.9},
		{"Jake Elliott", "K", "PHI", 7.8},
		{"Cairo Santos", "K", "CHI", 7.7},
		{"Younghoe Koo", "K", "ATL", 7.6},
		{"Jason Sanders", "K", "MIA", 7.5},
		{"Ravens D/ST", "DST", "BAL", 7.8},
		{"Steelers D/ST", "DST", "PIT", 7.6},
		{"Broncos D/ST", "DST", "DEN", 7.5},
		{"Eagles D/ST", "DST", "PHI", 7.4},
		{"Texans D/ST", "DST", "HOU", 7.3},
		{"Packers D/ST", "DST", "GB", 7.2},
		{"Vikings D/ST", "DST", "MIN", 7.1},
		{"Bills D/ST", "DST", "BUF", 7.0},
		{"Chiefs D/ST", "DST", "KC", 6.9},
		{"Lions D/ST", "DST", "DET", 6.8},
		{"Seahawks D/ST", "DST", "SEA", 6.7},
		{"Jets D/ST", "DST", "NYJ", 6.6},
	}
	players := make([]Player, 0, len(rows))
	for index, row := range rows {
		players = append(players, Player{
			ID:         "offline-" + row.team + "-" + slug(row.name),
			Name:       row.name,
			Position:   row.pos,
			NFLTeam:    row.team,
			ADP:        float64(index + 1),
			ADPRank:    index + 1,
			Projection: row.proj,
		})
	}
	return players
}

func slug(name string) string {
	out := make([]rune, 0, len(name))
	for _, r := range name {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9':
			out = append(out, r)
		case r >= 'A' && r <= 'Z':
			out = append(out, r+('a'-'A'))
		case r == ' ', r == '.', r == '\'', r == '/':
			if len(out) > 0 && out[len(out)-1] != '-' {
				out = append(out, '-')
			}
		}
	}
	for len(out) > 0 && out[len(out)-1] == '-' {
		out = out[:len(out)-1]
	}
	return string(out)
}
